import React from 'react';

function HomePage() {
  return (
    <div className='container mx-auto px-4 py-8'>
      <header className='bg-gradient-to-r from-gray-800 via-gray-700 to-gray-800 text-white p-10 rounded-lg shadow-2xl mb-12 text-center transform hover:scale-105 transition-transform duration-300'>
        <h1 className='text-5xl font-extrabold mb-4 tracking-tight'>The Ainstien</h1>
        <p className='text-xl text-gray-300'>
          Engage your intellect. Discover yourself.
        </p>
      </header>

      <main className='space-y-10'>
        {/* Card-like sections */}
        <section id='about' className='p-8 bg-white shadow-xl rounded-lg border border-gray-200 hover:shadow-2xl transition-shadow duration-300'>
          <h2 className='text-3xl font-bold text-gray-800 mb-5 border-b-2 border-indigo-500 pb-3'>About The Ainstien</h2>
          <div className='text-gray-700 space-y-3 leading-relaxed text-lg'>
            <p>
              The Ainstien is a unique web application crafted by Aniruddha Choudhary, designed to stimulate your mind and offer profound self-reflection through two primary features:
            </p>
            <ul className='list-none space-y-2 pl-0'>
              <li className='flex items-start'><span className='text-indigo-500 font-bold mr-2 text-2xl'>›</span> <strong>Ainstien Chatbot:</strong> Dive into philosophical dialogues with Ainstien, an AI that embodies a unique personality. It identifies as an alter ego of its creator and engages with human-like emotion and depth.</li>
              <li className='flex items-start'><span className='text-indigo-500 font-bold mr-2 text-2xl'>›</span> <strong>Personality Test:</strong> Embark on a journey of self-discovery with an 11-question personality test. Each question is freshly generated by AI, leading to a personalized and detailed analysis of your responses.</li>
            </ul>
          </div>
        </section>

        <div className='grid md:grid-cols-2 gap-10'>
          <section id='navigation-guide' className='p-8 bg-white shadow-xl rounded-lg border border-gray-200 hover:shadow-2xl transition-shadow duration-300'>
            <h2 className='text-3xl font-bold text-gray-800 mb-5 border-b-2 border-teal-500 pb-3'>Navigating the App</h2>
            <p className='text-gray-700 leading-relaxed text-lg'>
              Use the sleek navigation bar at the top to effortlessly switch between the Home page, the Ainstien Chatbot, the Personality Test, and our FAQ section. Each area is tailored for a distinct experience.
            </p>
          </section>

          <section id='usage' className='p-8 bg-white shadow-xl rounded-lg border border-gray-200 hover:shadow-2xl transition-shadow duration-300'>
            <h2 className='text-3xl font-bold text-gray-800 mb-5 border-b-2 border-purple-500 pb-3'>How to Use</h2>
            <div className='text-gray-700 space-y-4 leading-relaxed text-lg'>
              <p><strong>Chatbot:</strong> Visit 'Ainstien Chatbot'. Type your thoughts or philosophical questions. Await Ainstien\'s unique, thoughtful responses.</p>
              <p><strong>Personality Test:</strong> Head to 'Personality Test'. Answer 11 AI-generated questions. Submit to receive your detailed personality profile.</p>
            </div>
          </section>
        </div>
      </main>

      <footer className='text-center py-10 mt-16 text-gray-500 border-t border-gray-300'>
        <p>&copy; {new Date().getFullYear()} The Ainstien. Lovingly crafted by Aniruddha Choudhary.</p>
      </footer>
    </div>
  );
}
export default HomePage;
